### ISSUE TITLE
Branch names with umlauts are not supported

### ISSUE THREAD

**Issue by makmic** [makandra/gurney#2]
## Example 
```
git checkout -b ml/überraschung
git push
```

### Error
``` 
remote: /var/lib/gems/2.5.0/gems/gurney_client-0.2.1/lib/gurney/cli.rb:49:in `match': invalid byte sequence in US-ASCII (ArgumentError)
remote: 	from /var/lib/gems/2.5.0/gems/gurney_client-0.2.1/lib/gurney/cli.rb:49:in `match'
remote: 	from /var/lib/gems/2.5.0/gems/gurney_client-0.2.1/lib/gurney/cli.rb:49:in `block in run'
remote: 	from /var/lib/gems/2.5.0/gems/gurney_client-0.2.1/lib/gurney/cli.rb:47:in `each_line'
remote: 	from /var/lib/gems/2.5.0/gems/gurney_client-0.2.1/lib/gurney/cli.rb:47:in `run'
remote: 	from /var/lib/gems/2.5.0/gems/gurney_client-0.2.1/exe/gurney:5:in `<top (required)>'
remote: 	from /usr/local/bin/gurney:23:in `load'
remote: 	from /usr/local/bin/gurney:23:in `<main>'
remote: Gurney: an unexpected error occurred
```

**Comment by makmic** [comment]
I cannot easily reproduce it locally, it could be linked to the server's locale. This code _might_ help.

```
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
```

**Comment by codener** [comment]
Has been rolled out. Please verify.

**Comment by makmic** [comment]
Thank you, I cannot reproduce the reported issue anymore :bow:
